src/Entity/Serie.php
<?php

namespace App\Entity;

use App\Repository\SerieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SerieRepository::class)]
class Serie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $synopsis = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $affiche = null;

    #[ORM\OneToMany(mappedBy: 'serie', targetEntity: Commentaire::class, orphanRemoval: true)]
    private Collection $commentaires;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'series')]
    private Collection $genres;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(?string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(?string $affiche): self
    {
        $this->affiche = $affiche;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setSerie($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getSerie() === $this) {
                $commentaire->setSerie(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }

    public function getGenresTexte()
    {
        $texte = "";
        foreach ($this->genres as $genre) {
            $texte .= ($texte ? ", " : "") . $genre->getLibelle();
        }

        return $texte;
    }

}

src/Form/SerieType.php
<?php

namespace App\Form;

use App\Entity\Serie, App\Entity\Genre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class SerieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('synopsis')
            ->add('affiche', FileType::class, [
                "mapped"    => false,
                "required"  => false
            ])
            ->add('genres', EntityType::class, [
                "class"         => Genre::class,
                "choice_label"  => "libelle",
                "multiple"      => true,
                "expanded"      => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Serie::class,
        ]);
    }
}

src/Controller/Admin/SerieController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Serie;
use App\Form\SerieType;
use App\Repository\SerieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/serie')]
class SerieController extends AbstractController
{
    #[Route('/', name: 'app_admin_serie_index', methods: ['GET'])]
    public function index(SerieRepository $serieRepository): Response
    {
        return $this->render('admin/serie/index.html.twig', [
            'series' => $serieRepository->findAll(),
        ]);
    }

    #[Route('/ajouter', name: 'app_admin_serie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SerieRepository $serieRepository): Response
    {
        $serie = new Serie();
        $form = $this->createForm(SerieType::class, $serie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serieRepository->add($serie, true);

            return $this->redirectToRoute('app_admin_serie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/serie/new.html.twig', [
            'serie' => $serie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_serie_show', methods: ['GET'])]
    public function show(Serie $serie): Response
    {
        return $this->render('admin/serie/show.html.twig', [
            'serie' => $serie,
        ]);
    }

    #[Route('/{id}/modifier', name: 'app_admin_serie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Serie $serie, SerieRepository $serieRepository): Response
    {
        $form = $this->createForm(SerieType::class, $serie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serieRepository->add($serie, true);

            return $this->redirectToRoute('app_admin_serie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/serie/edit.html.twig', [
            'serie' => $serie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_serie_delete', methods: ['POST'])]
    public function delete(Request $request, Serie $serie, SerieRepository $serieRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$serie->getId(), $request->request->get('_token'))) {
            $serieRepository->remove($serie, true);
        }

        return $this->redirectToRoute('app_admin_serie_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/SerieController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Serie;
use App\Repository\CommentaireRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SerieController extends AbstractController
{
    #[Route('/serie', name: 'app_serie')]
    public function index(): Response
    {
        return $this->render('serie/index.html.twig', [
            'controller_name' => 'SerieController',
        ]);
    }

    #[Route('/commenter-la-serie-{id}', name: 'app_serie_comment')]
    #[IsGranted("IS_AUTHENTICATED_FULLY")]
    public function comment(Serie $serie, Request $request, CommentaireRepository $cr): Response
    {
        $commentaire = new Commentaire;
        
        if( $request->isMethod("POST")){
            $commentaire->setSerie($serie);
            $commentaire->setUser( $this->getUser() );
            $commentaire->setSujet( $request->request->get("sujet") );
            $commentaire->setTexte( $request->request->get("texte") );
            $cr->add($commentaire, true);
        }
        return $this->render('serie/fiche.html.twig', [
            'serie' => $serie,
        ]);
    }
}

templates/serie/card.html.twig
<div class="card livre">
    <h4 class="card-header">{{ serie.titre }}</h4>

    <div class="row ">
        <div class="col-4 d-flex align-items-center">
            <img class="card-img p-1" src="">
        </div>

        <div class="col-8">
            <div class="card-body">
                <p class="card-text">Genres : {{ serie.genresTexte }} 
            </div>
        </div>
    </div>

    <div class="card-footer">
            <a href="{{ path('app_serie_comment', {id: serie.id}) }}" class="card-link">
                <i class="fa fa-book"></i> Commenter
            </a>
        
    </div>
</div>  

templates/serie/commentaire_card.html.twig
<div class=" ">
    <h4 class="card-header">{{ commentaire.sujet }}</h4>

    <div class="row ">
        <div class="col-8">
            <div class="card-body">
                <p class="card-text">De : <i>{{ commentaire.user.pseudo }}</i> 
                <p class="card-text">{{ commentaire.texte }} 
            </div>
        </div>
    </div>
</div>  

templates/serie/fiche.html.twig
{% extends 'base.html.twig' %}

{% block title %}Serie{% endblock %}

{% block body %}
    <h1>Fiche Série</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ serie.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ serie.titre }}</td>
            </tr>
            <tr>
                <th>Synopsis</th>
                <td>{{ serie.synopsis }}</td>
            </tr>
            <tr>
                <th>Affiche</th>
                <td>{{ serie.affiche }}</td>
            </tr>

            <tr>
                <th>Commentaires</th>
                <td>
                    {% for commentaire in serie.commentaires %}
                        {{ include ("serie/commentaire_card.html.twig") }}
                    {% else %}
                        <tr>
                            <td colspan="4">Aucun commentaire</td>
                        </tr>
                    {% endfor %}
            

                </td>
            </tr>
        </tbody>
    </table>

    <form action="" method="post">
        <div class="form-group">
            <label for="">Sujet</label>
            <input type="text" class="form-control" name="sujet">
        </div>
        <div class="form-group">
            <label for="">Commentaire</label>
            <input type="text" class="form-control" name="texte">
        </div>
        <button class="btn btn-primary">Poster un commentaire</button>
    </form>
{% endblock %}

templates/serie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SerieController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/blogserie/src/Controller/SerieController.php'|file_link(0) }}">src/Controller/SerieController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/blogserie/templates/serie/index.html.twig'|file_link(0) }}">templates/serie/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}